[tool.pyright]
include = ["nfvsmotifs", "tests"]
stubPath = "stubs"
reportMissingImports = true
reportMissingTypeStubs = true
reportUntypedFunctionDecorator = true
reportUntypedClassDecorator = true
typeCheckingMode = "strict"

[tool.mypy]
mypy_path = "stubs"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 88
profile = "black"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--networksize=10"
