name: test
on:
  push:
    branches:
      - main
permissions: # so we can upload the docs
  contents: write

jobs:
  docs-build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install clingo
        run: sudo apt-get -y install gringo
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          architecture: x64
      - name: Install repo dependencies
        run: pip install -r requirements.txt
      - name: Install sphinx requirements
        run: pip install sphinx sphinx-toolbox pydata-sphinx-theme sphinx-copybutton sphinx-autoapi
      - name: Build docs
        run: |
          sphinx-build -M html docs/source/ docs/build/
      - name: deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build/html
          single-commit: true