name: test
on:
  pull_request:
    types:
      - closed
permissions: # so we can upload the docs
  contents: write

jobs:
  docs-build-and-deploy:
    # only on merged PR
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install clingo
        run: sudo apt-get -y install gringo
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          architecture: x64
      - name: Install repo dependencies
        run: pip install -r requirements.txt
      - name: Install sphinx requirements
        run: pip install sphinx sphinx-toolbox pydata-sphinx-theme sphinx-copybutton sphinx-autoapi
      - uses: actions/checkout@v1
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
      - name: deploy docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_build/ # The folder the action should deploy.