name: test
on:
  push:
  pull_request:

jobs:
  linux:
    # TODO: Later we can add more python versions but for now one should be enough.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install clingo
        run: sudo apt-get -y install gringo
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          architecture: x64
      - name: Install repo dependencies
        run: pip install -r requirements.txt
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy check
        run: mypy src
      - name: Install pytest
        run: pip install pytest pytest-md pytest-emoji      
      - name: Run pytest
        run: pytest